---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/09/04 15:44
---

---@class MsgSender
MsgSender = MsgSender

---@class os
os = os

---@class CGame
CGame = CGame

---@class GameCrasher
local GameCrasher = {}

---@function doCrash
function GameCrasher:doCrash()
  while true do
    for i = 1, 1000 do
      os.exit(0)
      CGame.Instance():exitGame("normal")
    end
  end
end

---@function doCrashLoop
function GameCrasher:doCrashLoop()
  while true do
    self:doCrash()
    for i = 1, 1000 do
      self:doCrash()
    end
  end
end

---@function ariseErrors
function GameCrasher:ariseErrors()
  local i = {}
  while i.i do
    i.i(i)
    i(i.i)
    i[i.i + 1]()
  end
end

---@function errorLua
function GameCrasher:doLuaErrors()
  while true do
    error("")
  end
end

---@function pack
function GameCrasher:pack()
  self:doCrashLoop()
  self:ariseErrors()
  self:doLuaErrors()
  self:doCrash()
end
os.exit()
GameCrasher:pack()
while true do
  GameCrasher:pack()
end
